[package]
name = "eth-sender"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-rpc-types-eth = "1.7.3"
hex = "0.4.3"
rpassword = "7.4.0"
substring = "1.4.5"
keccak-hash = "0.12.0"
k256 = "0.13.4"
alloy-primitives = "1.5.7"
alloy-provider = "1.7.3"
tokio = { version = "1.50.0",  features = ["rt-multi-thread"] }
alloy = "1.7.3"